"""add image and descripton to Category model.

Revision ID: 753936a87751
Revises: 6fc132f640d2
Create Date: 2023-10-28 20:17:55.809290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753936a87751'
down_revision = '6fc132f640d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
